// countries.ts
interface Country {
  name: string;
  isoCode: string;
  currencyCode: string;
  currencyName: string;
  phoneCode: string;
  flag: string;
}

const countries: Country[] = [
  {
    name: "Afghanistan",
    isoCode: "AF",
    currencyCode: "AFN",
    currencyName: "Afghani",
    phoneCode: "+93",
    flag: "🇦🇫",
  },
  {
    name: "Albania",
    isoCode: "AL",
    currencyCode: "ALL",
    currencyName: "Lek",
    phoneCode: "+355",
    flag: "🇦🇱",
  },
  {
    name: "Algeria",
    isoCode: "DZ",
    currencyCode: "DZD",
    currencyName: "Dinar",
    phoneCode: "+213",
    flag: "🇩🇿",
  },
  {
    name: "American Samoa",
    isoCode: "AS",
    currencyCode: "USD",
    currencyName: "US Dollar",
    phoneCode: "+1-684",
    flag: "🇦🇸",
  },
  {
    name: "Andorra",
    isoCode: "AD",
    currencyCode: "EUR",
    currencyName: "Euro",
    phoneCode: "+376",
    flag: "🇦🇩",
  },
  {
    name: "Angola",
    isoCode: "AO",
    currencyCode: "AOA",
    currencyName: "Kwanza",
    phoneCode: "+244",
    flag: "🇦🇴",
  },
  {
    name: "Anguilla",
    isoCode: "AI",
    currencyCode: "XCD",
    currencyName: "East Caribbean Dollar",
    phoneCode: "+1-264",
    flag: "🇦🇮",
  },
  {
    name: "Antarctica",
    isoCode: "AQ",
    currencyCode: "none",
    currencyName: "None",
    phoneCode: "+672",
    flag: "🇦🇶",
  },
  {
    name: "Antigua and Barbuda",
    isoCode: "AG",
    currencyCode: "XCD",
    currencyName: "East Caribbean Dollar",
    phoneCode: "+1-268",
    flag: "🇦🇬",
  },
  {
    name: "Argentina",
    isoCode: "AR",
    currencyCode: "ARS",
    currencyName: "Argentine Peso",
    phoneCode: "+54",
    flag: "🇦🇷",
  },
  {
    name: "Armenia",
    isoCode: "AM",
    currencyCode: "AMD",
    currencyName: "Dram",
    phoneCode: "+374",
    flag: "🇦🇲",
  },
  {
    name: "Aruba",
    isoCode: "AW",
    currencyCode: "AWG",
    currencyName: "Aruban Florin",
    phoneCode: "+297",
    flag: "🇦🇼",
  },
  {
    name: "Australia",
    isoCode: "AU",
    currencyCode: "AUD",
    currencyName: "Australian Dollar",
    phoneCode: "+61",
    flag: "🇦🇺",
  },
  {
    name: "Austria",
    isoCode: "AT",
    currencyCode: "EUR",
    currencyName: "Euro",
    phoneCode: "+43",
    flag: "🇦🇹",
  },
  {
    name: "Azerbaijan",
    isoCode: "AZ",
    currencyCode: "AZN",
    currencyName: "Manat",
    phoneCode: "+994",
    flag: "🇦🇿",
  },
  {
    name: "Bahamas",
    isoCode: "BS",
    currencyCode: "BSD",
    currencyName: "Bahamian Dollar",
    phoneCode: "+1-242",
    flag: "🇧🇸",
  },
  {
    name: "Bahrain",
    isoCode: "BH",
    currencyCode: "BHD",
    currencyName: "Bahraini Dinar",
    phoneCode: "+973",
    flag: "🇧🇭",
  },
  {
    name: "Bangladesh",
    isoCode: "BD",
    currencyCode: "BDT",
    currencyName: "Taka",
    phoneCode: "+880",
    flag: "🇧🇩",
  },
  {
    name: "Barbados",
    isoCode: "BB",
    currencyCode: "BBD",
    currencyName: "Barbadian Dollar",
    phoneCode: "+1-246",
    flag: "🇧🇧",
  },
  {
    name: "Belarus",
    isoCode: "BY",
    currencyCode: "BYN",
    currencyName: "Belarusian Ruble",
    phoneCode: "+375",
    flag: "🇧🇾",
  },
  {
    name: "Belgium",
    isoCode: "BE",
    currencyCode: "EUR",
    currencyName: "Euro",
    phoneCode: "+32",
    flag: "🇧🇪",
  },
  {
    name: "Belize",
    isoCode: "BZ",
    currencyCode: "BZD",
    currencyName: "Belize Dollar",
    phoneCode: "+501",
    flag: "🇧🇿",
  },
  {
    name: "Benin",
    isoCode: "BJ",
    currencyCode: "XOF",
    currencyName: "West African CFA Franc",
    phoneCode: "+229",
    flag: "🇧🇯",
  },
  {
    name: "Bermuda",
    isoCode: "BM",
    currencyCode: "BMD",
    currencyName: "Bermudian Dollar",
    phoneCode: "+1-441",
    flag: "🇧🇲",
  },
  {
    name: "Bhutan",
    isoCode: "BT",
    currencyCode: "BTN",
    currencyName: "Ngultrum",
    phoneCode: "+975",
    flag: "🇧🇹",
  },
  {
    name: "Bolivia",
    isoCode: "BO",
    currencyCode: "BOB",
    currencyName: "Boliviano",
    phoneCode: "+591",
    flag: "🇧🇴",
  },
  {
    name: "Bonaire, Sint Eustatius and Saba",
    isoCode: "BQ",
    currencyCode: "USD",
    currencyName: "US Dollar",
    phoneCode: "+599",
    flag: "🇧🇶",
  },
  {
    name: "Bosnia and Herzegovina",
    isoCode: "BA",
    currencyCode: "BAM",
    currencyName: "Convertible Mark",
    phoneCode: "+387",
    flag: "🇧🇦",
  },
  {
    name: "Botswana",
    isoCode: "BW",
    currencyCode: "BWP",
    currencyName: "Pula",
    phoneCode: "+267",
    flag: "🇧🇼",
  },
  {
    name: "Bouvet Island",
    isoCode: "BV",
    currencyCode: "NOK",
    currencyName: "Norwegian Krone",
    phoneCode: "+47",
    flag: "🇧🇻",
  },
  {
    name: "Brazil",
    isoCode: "BR",
    currencyCode: "BRL",
    currencyName: "Real",
    phoneCode: "+55",
    flag: "🇧🇷",
  },
  {
    name: "British Indian Ocean Territory",
    isoCode: "IO",
    currencyCode: "USD",
    currencyName: "US Dollar",
    phoneCode: "+246",
    flag: "🇮🇴",
  },
  {
    name: "Brunei Darussalam",
    isoCode: "BN",
    currencyCode: "BND",
    currencyName: "Brunei Dollar",
    phoneCode: "+673",
    flag: "🇧🇳",
  },
  {
    name: "Bulgaria",
    isoCode: "BG",
    currencyCode: "BGN",
    currencyName: "Lev",
    phoneCode: "+359",
    flag: "🇧🇬",
  },
  {
    name: "Burkina Faso",
    isoCode: "BF",
    currencyCode: "XOF",
    currencyName: "West African CFA Franc",
    phoneCode: "+226",
    flag: "🇧🇫",
  },
  {
    name: "Burundi",
    isoCode: "BI",
    currencyCode: "BIF",
    currencyName: "Burundi Franc",
    phoneCode: "+257",
    flag: "🇧🇮",
  },
  {
    name: "Cabo Verde",
    isoCode: "CV",
    currencyCode: "CVE",
    currencyName: "Cabo Verde Escudo",
    phoneCode: "+238",
    flag: "🇨🇻",
  },
  {
    name: "Cambodia",
    isoCode: "KH",
    currencyCode: "KHR",
    currencyName: "Riel",
    phoneCode: "+855",
    flag: "🇰🇭",
  },
  {
    name: "Cameroon",
    isoCode: "CM",
    currencyCode: "XAF",
    currencyName: "Central African CFA Franc",
    phoneCode: "+237",
    flag: "🇨🇲",
  },
  {
    name: "Canada",
    isoCode: "CA",
    currencyCode: "CAD",
    currencyName: "Canadian Dollar",
    phoneCode: "+1",
    flag: "🇨🇦",
  },
  {
    name: "Cayman Islands",
    isoCode: "KY",
    currencyCode: "KYD",
    currencyName: "Cayman Islands Dollar",
    phoneCode: "+1-345",
    flag: "🇰🇾",
  },
  {
    name: "Central African Republic",
    isoCode: "CF",
    currencyCode: "XAF",
    currencyName: "Central African CFA Franc",
    phoneCode: "+236",
    flag: "🇨🇫",
  },
  {
    name: "Chad",
    isoCode: "TD",
    currencyCode: "XAF",
    currencyName: "Central African CFA Franc",
    phoneCode: "+235",
    flag: "🇹🇩",
  },
  {
    name: "Chile",
    isoCode: "CL",
    currencyCode: "CLP",
    currencyName: "Chilean Peso",
    phoneCode: "+56",
    flag: "🇨🇱",
  },
  {
    name: "China",
    isoCode: "CN",
    currencyCode: "CNY",
    currencyName: "Yuan",
    phoneCode: "+86",
    flag: "🇨🇳",
  },
  {
    name: "Christmas Island",
    isoCode: "CX",
    currencyCode: "AUD",
    currencyName: "Australian Dollar",
    phoneCode: "+61",
    flag: "🇨🇽",
  },
  {
    name: "Cocos (Keeling) Islands",
    isoCode: "CC",
    currencyCode: "AUD",
    currencyName: "Australian Dollar",
    phoneCode: "+61",
    flag: "🇨🇨",
  },
  {
    name: "Colombia",
    isoCode: "CO",
    currencyCode: "COP",
    currencyName: "Colombian Peso",
    phoneCode: "+57",
    flag: "🇨🇴",
  },
  {
    name: "Comoros",
    isoCode: "KM",
    currencyCode: "KMF",
    currencyName: "Comorian Franc",
    phoneCode: "+269",
    flag: "🇰🇲",
  },
  {
    name: "Congo",
    isoCode: "CG",
    currencyCode: "XAF",
    currencyName: "Central African CFA Franc",
    phoneCode: "+242",
    flag: "🇨🇬",
  },
  {
    name: "Congo, Democratic Republic of the",
    isoCode: "CD",
    currencyCode: "CDF",
    currencyName: "Congolese Franc",
    phoneCode: "+243",
    flag: "🇨🇩",
  },
  {
    name: "Cook Islands",
    isoCode: "CK",
    currencyCode: "NZD",
    currencyName: "New Zealand Dollar",
    phoneCode: "+682",
    flag: "🇨🇰",
  },
  {
    name: "Costa Rica",
    isoCode: "CR",
    currencyCode: "CRC",
    currencyName: "Costa Rican Colón",
    phoneCode: "+506",
    flag: "🇨🇷",
  },
  {
    name: "Côte d'Ivoire",
    isoCode: "CI",
    currencyCode: "XOF",
    currencyName: "West African CFA Franc",
    phoneCode: "+225",
    flag: "🇨🇮",
  },
  {
    name: "Croatia",
    isoCode: "HR",
    currencyCode: "EUR",
    currencyName: "Euro",
    phoneCode: "+385",
    flag: "🇭🇷",
  },
  {
    name: "Cuba",
    isoCode: "CU",
    currencyCode: "CUP",
    currencyName: "Cuban Peso",
    phoneCode: "+53",
    flag: "🇨🇺",
  },
  {
    name: "Curaçao",
    isoCode: "CW",
    currencyCode: "ANG",
    currencyName: "Netherlands Antillean Guilder",
    phoneCode: "+599",
    flag: "🇨🇼",
  },
  {
    name: "Cyprus",
    isoCode: "CY",
    currencyCode: "EUR",
    currencyName: "Euro",
    phoneCode: "+357",
    flag: "🇨🇾",
  },
  {
    name: "Czechia",
    isoCode: "CZ",
    currencyCode: "CZK",
    currencyName: "Czech Koruna",
    phoneCode: "+420",
    flag: "🇨🇿",
  },
  {
    name: "Denmark",
    isoCode: "DK",
    currencyCode: "DKK",
    currencyName: "Danish Krone",
    phoneCode: "+45",
    flag: "🇩🇰",
  },
  {
    name: "Djibouti",
    isoCode: "DJ",
    currencyCode: "DJF",
    currencyName: "Djiboutian Franc",
    phoneCode: "+253",
    flag: "🇩🇯",
  },
  {
    name: "Dominica",
    isoCode: "DM",
    currencyCode: "XCD",
    currencyName: "East Caribbean Dollar",
    phoneCode: "+1-767",
    flag: "🇩🇲",
  },
  {
    name: "Dominican Republic",
    isoCode: "DO",
    currencyCode: "DOP",
    currencyName: "Dominican Peso",
    phoneCode: "+1-809",
    flag: "🇩🇴",
  },
  {
    name: "Ecuador",
    isoCode: "EC",
    currencyCode: "USD",
    currencyName: "US Dollar",
    phoneCode: "+593",
    flag: "🇪🇨",
  },
  {
    name: "Egypt",
    isoCode: "EG",
    currencyCode: "EGP",
    currencyName: "Egyptian Pound",
    phoneCode: "+20",
    flag: "🇪🇬",
  },
  {
    name: "El Salvador",
    isoCode: "SV",
    currencyCode: "USD",
    currencyName: "US Dollar",
    phoneCode: "+503",
    flag: "🇸🇻",
  },
  {
    name: "Equatorial Guinea",
    isoCode: "GQ",
    currencyCode: "XAF",
    currencyName: "Central African CFA Franc",
    phoneCode: "+240",
    flag: "🇬🇶",
  },
  {
    name: "Eritrea",
    isoCode: "ER",
    currencyCode: "ERN",
    currencyName: "Nakfa",
    phoneCode: "+291",
    flag: "🇪🇷",
  },
  {
    name: "Estonia",
    isoCode: "EE",
    currencyCode: "EUR",
    currencyName: "Euro",
    phoneCode: "+372",
    flag: "🇪🇪",
  },
  {
    name: "Eswatini",
    isoCode: "SZ",
    currencyCode: "SZL",
    currencyName: "Lilangeni",
    phoneCode: "+268",
    flag: "🇸🇿",
  },
  {
    name: "Ethiopia",
    isoCode: "ET",
    currencyCode: "ETB",
    currencyName: "Birr",
    phoneCode: "+251",
    flag: "🇪🇹",
  },
  {
    name: "Falkland Islands",
    isoCode: "FK",
    currencyCode: "FKP",
    currencyName: "Falkland Islands Pound",
    phoneCode: "+500",
    flag: "🇫🇰",
  },
  {
    name: "Faroe Islands",
    isoCode: "FO",
    currencyCode: "DKK",
    currencyName: "Danish Krone",
    phoneCode: "+298",
    flag: "🇫🇴",
  },
  {
    name: "Fiji",
    isoCode: "FJ",
    currencyCode: "FJD",
    currencyName: "Fijian Dollar",
    phoneCode: "+679",
    flag: "🇫🇯",
  },
  {
    name: "Finland",
    isoCode: "FI",
    currencyCode: "EUR",
    currencyName: "Euro",
    phoneCode: "+358",
    flag: "🇫🇮",
  },
  {
    name: "France",
    isoCode: "FR",
    currencyCode: "EUR",
    currencyName: "Euro",
    phoneCode: "+33",
    flag: "🇫🇷",
  },
  {
    name: "French Guiana",
    isoCode: "GF",
    currencyCode: "EUR",
    currencyName: "Euro",
    phoneCode: "+594",
    flag: "🇬🇫",
  },
  {
    name: "French Polynesia",
    isoCode: "PF",
    currencyCode: "XPF",
    currencyName: "CFP Franc",
    phoneCode: "+689",
    flag: "🇵🇫",
  },
  {
    name: "French Southern Territories",
    isoCode: "TF",
    currencyCode: "EUR",
    currencyName: "Euro",
    phoneCode: "+262",
    flag: "🇹🇫",
  },
  {
    name: "Gabon",
    isoCode: "GA",
    currencyCode: "XAF",
    currencyName: "Central African CFA Franc",
    phoneCode: "+241",
    flag: "🇬🇦",
  },
  {
    name: "Gambia",
    isoCode: "GM",
    currencyCode: "GMD",
    currencyName: "Dalasi",
    phoneCode: "+220",
    flag: "🇬🇲",
  },
  {
    name: "Georgia",
    isoCode: "GE",
    currencyCode: "GEL",
    currencyName: "Lari",
    phoneCode: "+995",
    flag: "🇬🇪",
  },
  {
    name: "Germany",
    isoCode: "DE",
    currencyCode: "EUR",
    currencyName: "Euro",
    phoneCode: "+49",
    flag: "🇩🇪",
  },
  {
    name: "Ghana",
    isoCode: "GH",
    currencyCode: "GHS",
    currencyName: "Cedi",
    phoneCode: "+233",
    flag: "🇬🇭",
  },
  {
    name: "Gibraltar",
    isoCode: "GI",
    currencyCode: "GIP",
    currencyName: "Gibraltar Pound",
    phoneCode: "+350",
    flag: "🇬🇮",
  },
  {
    name: "Greece",
    isoCode: "GR",
    currencyCode: "EUR",
    currencyName: "Euro",
    phoneCode: "+30",
    flag: "🇬🇷",
  },
  {
    name: "Greenland",
    isoCode: "GL",
    currencyCode: "DKK",
    currencyName: "Danish Krone",
    phoneCode: "+299",
    flag: "🇬🇱",
  },
  {
    name: "Grenada",
    isoCode: "GD",
    currencyCode: "XCD",
    currencyName: "East Caribbean Dollar",
    phoneCode: "+1-473",
    flag: "🇬🇩",
  },
  {
    name: "Guadeloupe",
    isoCode: "GP",
    currencyCode: "EUR",
    currencyName: "Euro",
    phoneCode: "+590",
    flag: "🇬🇵",
  },
  {
    name: "Guam",
    isoCode: "GU",
    currencyCode: "USD",
    currencyName: "US Dollar",
    phoneCode: "+1-671",
    flag: "🇬🇺",
  },
  {
    name: "Guatemala",
    isoCode: "GT",
    currencyCode: "GTQ",
    currencyName: "Quetzal",
    phoneCode: "+502",
    flag: "🇬🇹",
  },
  {
    name: "Guernsey",
    isoCode: "GG",
    currencyCode: "GBP",
    currencyName: "Pound Sterling",
    phoneCode: "+44-1481",
    flag: "🇬🇬",
  },
  {
    name: "Guinea",
    isoCode: "GN",
    currencyCode: "GNF",
    currencyName: "Guinean Franc",
    phoneCode: "+224",
    flag: "🇬🇳",
  },
  {
    name: "Guinea-Bissau",
    isoCode: "GW",
    currencyCode: "XOF",
    currencyName: "West African CFA Franc",
    phoneCode: "+245",
    flag: "🇬🇼",
  },
  {
    name: "Guyana",
    isoCode: "GY",
    currencyCode: "GYD",
    currencyName: "Guyanese Dollar",
    phoneCode: "+592",
    flag: "🇬🇾",
  },
  {
    name: "Haiti",
    isoCode: "HT",
    currencyCode: "HTG",
    currencyName: "Gourde",
    phoneCode: "+509",
    flag: "🇭🇹",
  },
  {
    name: "Heard Island and McDonald Islands",
    isoCode: "HM",
    currencyCode: "AUD",
    currencyName: "Australian Dollar",
    phoneCode: "+672",
    flag: "🇭🇲",
  },
  {
    name: "Holy See",
    isoCode: "VA",
    currencyCode: "EUR",
    currencyName: "Euro",
    phoneCode: "+39-06",
    flag: "🇻🇦",
  },
  {
    name: "Honduras",
    isoCode: "HN",
    currencyCode: "HNL",
    currencyName: "Lempira",
    phoneCode: "+504",
    flag: "🇭🇳",
  },
  {
    name: "Hong Kong",
    isoCode: "HK",
    currencyCode: "HKD",
    currencyName: "Hong Kong Dollar",
    phoneCode: "+852",
    flag: "🇭🇰",
  },
  {
    name: "Hungary",
    isoCode: "HU",
    currencyCode: "HUF",
    currencyName: "Forint",
    phoneCode: "+36",
    flag: "🇭🇺",
  },
  {
    name: "Iceland",
    isoCode: "IS",
    currencyCode: "ISK",
    currencyName: "Icelandic Króna",
    phoneCode: "+354",
    flag: "🇮🇸",
  },
  {
    name: "India",
    isoCode: "IN",
    currencyCode: "INR",
    currencyName: "Indian Rupee",
    phoneCode: "+91",
    flag: "🇮🇳",
  },
  {
    name: "Indonesia",
    isoCode: "ID",
    currencyCode: "IDR",
    currencyName: "Rupiah",
    phoneCode: "+62",
    flag: "🇮🇩",
  },
  {
    name: "Iran",
    isoCode: "IR",
    currencyCode: "IRR",
    currencyName: "Iranian Rial",
    phoneCode: "+98",
    flag: "🇮🇷",
  },
  {
    name: "Iraq",
    isoCode: "IQ",
    currencyCode: "IQD",
    currencyName: "Iraqi Dinar",
    phoneCode: "+964",
    flag: "🇮🇶",
  },
  {
    name: "Ireland",
    isoCode: "IE",
    currencyCode: "EUR",
    currencyName: "Euro",
    phoneCode: "+353",
    flag: "🇮🇪",
  },
  {
    name: "Isle of Man",
    isoCode: "IM",
    currencyCode: "GBP",
    currencyName: "Pound Sterling",
    phoneCode: "+44-1624",
    flag: "🇮🇲",
  },
  {
    name: "Israel",
    isoCode: "IL",
    currencyCode: "ILS",
    currencyName: "New Shekel",
    phoneCode: "+972",
    flag: "🇮🇱",
  },
  {
    name: "Italy",
    isoCode: "IT",
    currencyCode: "EUR",
    currencyName: "Euro",
    phoneCode: "+39",
    flag: "🇮🇹",
  },
  {
    name: "Jamaica",
    isoCode: "JM",
    currencyCode: "JMD",
    currencyName: "Jamaican Dollar",
    phoneCode: "+1-876",
    flag: "🇯🇲",
  },
  {
    name: "Japan",
    isoCode: "JP",
    currencyCode: "JPY",
    currencyName: "Yen",
    phoneCode: "+81",
    flag: "🇯🇵",
  },
  {
    name: "Jersey",
    isoCode: "JE",
    currencyCode: "GBP",
    currencyName: "Pound Sterling",
    phoneCode: "+44-1534",
    flag: "🇯🇪",
  },
  {
    name: "Jordan",
    isoCode: "JO",
    currencyCode: "JOD",
    currencyName: "Jordanian Dinar",
    phoneCode: "+962",
    flag: "🇯🇴",
  },
  {
    name: "Kazakhstan",
    isoCode: "KZ",
    currencyCode: "KZT",
    currencyName: "Tenge",
    phoneCode: "+7",
    flag: "🇰🇿",
  },
  {
    name: "Kenya",
    isoCode: "KE",
    currencyCode: "KES",
    currencyName: "Kenyan Shilling",
    phoneCode: "+254",
    flag: "🇰🇪",
  },
  {
    name: "Kiribati",
    isoCode: "KI",
    currencyCode: "AUD",
    currencyName: "Australian Dollar",
    phoneCode: "+686",
    flag: "🇰🇮",
  },
  {
    name: "Korea, Democratic People's Republic of",
    isoCode: "KP",
    currencyCode: "KPW",
    currencyName: "North Korean Won",
    phoneCode: "+850",
    flag: "🇰🇵",
  },
  {
    name: "Korea, Republic of",
    isoCode: "KR",
    currencyCode: "KRW",
    currencyName: "South Korean Won",
    phoneCode: "+82",
    flag: "🇰🇷",
  },
  {
    name: "Kuwait",
    isoCode: "KW",
    currencyCode: "KWD",
    currencyName: "Kuwaiti Dinar",
    phoneCode: "+965",
    flag: "🇰🇼",
  },
  {
    name: "Kyrgyzstan",
    isoCode: "KG",
    currencyCode: "KGS",
    currencyName: "Som",
    phoneCode: "+996",
    flag: "🇰🇬",
  },
  {
    name: "Lao People's Democratic Republic",
    isoCode: "LA",
    currencyCode: "LAK",
    currencyName: "Kip",
    phoneCode: "+856",
    flag: "🇱🇦",
  },
  {
    name: "Latvia",
    isoCode: "LV",
    currencyCode: "EUR",
    currencyName: "Euro",
    phoneCode: "+371",
    flag: "🇱🇻",
  },
  {
    name: "Lebanon",
    isoCode: "LB",
    currencyCode: "LBP",
    currencyName: "Lebanese Pound",
    phoneCode: "+961",
    flag: "🇱🇧",
  },
  {
    name: "Lesotho",
    isoCode: "LS",
    currencyCode: "LSL",
    currencyName: "Loti",
    phoneCode: "+266",
    flag: "🇱🇸",
  },
  {
    name: "Liberia",
    isoCode: "LR",
    currencyCode: "LRD",
    currencyName: "Liberian Dollar",
    phoneCode: "+231",
    flag: "🇱🇷",
  },
  {
    name: "Libya",
    isoCode: "LY",
    currencyCode: "LYD",
    currencyName: "Libyan Dinar",
    phoneCode: "+218",
    flag: "🇱🇾",
  },
  {
    name: "Liechtenstein",
    isoCode: "LI",
    currencyCode: "CHF",
    currencyName: "Swiss Franc",
    phoneCode: "+423",
    flag: "🇱🇮",
  },
  {
    name: "Lithuania",
    isoCode: "LT",
    currencyCode: "EUR",
    currencyName: "Euro",
    phoneCode: "+370",
    flag: "🇱🇹",
  },
  {
    name: "Luxembourg",
    isoCode: "LU",
    currencyCode: "EUR",
    currencyName: "Euro",
    phoneCode: "+352",
    flag: "🇱🇺",
  },
  {
    name: "Macao",
    isoCode: "MO",
    currencyCode: "MOP",
    currencyName: "Pataca",
    phoneCode: "+853",
    flag: "🇲🇴",
  },
  {
    name: "Madagascar",
    isoCode: "MG",
    currencyCode: "MGA",
    currencyName: "Ariary",
    phoneCode: "+261",
    flag: "🇲🇬",
  },
  {
    name: "Malawi",
    isoCode: "MW",
    currencyCode: "MWK",
    currencyName: "Kwacha",
    phoneCode: "+265",
    flag: "🇲🇼",
  },
  {
    name: "Malaysia",
    isoCode: "MY",
    currencyCode: "MYR",
    currencyName: "Ringgit",
    phoneCode: "+60",
    flag: "🇲🇾",
  },
  {
    name: "Maldives",
    isoCode: "MV",
    currencyCode: "MVR",
    currencyName: "Rufiyaa",
    phoneCode: "+960",
    flag: "🇲🇻",
  },
  {
    name: "Mali",
    isoCode: "ML",
    currencyCode: "XOF",
    currencyName: "West African CFA Franc",
    phoneCode: "+223",
    flag: "🇲🇱",
  },
  {
    name: "Malta",
    isoCode: "MT",
    currencyCode: "EUR",
    currencyName: "Euro",
    phoneCode: "+356",
    flag: "🇲🇹",
  },
  {
    name: "Marshall Islands",
    isoCode: "MH",
    currencyCode: "USD",
    currencyName: "US Dollar",
    phoneCode: "+692",
    flag: "🇲🇭",
  },
  {
    name: "Martinique",
    isoCode: "MQ",
    currencyCode: "EUR",
    currencyName: "Euro",
    phoneCode: "+596",
    flag: "🇲🇶",
  },
  {
    name: "Mauritania",
    isoCode: "MR",
    currencyCode: "MRU",
    currencyName: "Ouguiya",
    phoneCode: "+222",
    flag: "🇲🇷",
  },
  {
    name: "Mauritius",
    isoCode: "MU",
    currencyCode: "MUR",
    currencyName: "Mauritian Rupee",
    phoneCode: "+230",
    flag: "🇲🇺",
  },
  {
    name: "Mayotte",
    isoCode: "YT",
    currencyCode: "EUR",
    currencyName: "Euro",
    phoneCode: "+262",
    flag: "🇾🇹",
  },
  {
    name: "Mexico",
    isoCode: "MX",
    currencyCode: "MXN",
    currencyName: "Mexican Peso",
    phoneCode: "+52",
    flag: "🇲🇽",
  },
  {
    name: "Micronesia, Federated States of",
    isoCode: "FM",
    currencyCode: "USD",
    currencyName: "US Dollar",
    phoneCode: "+691",
    flag: "🇫🇲",
  },
  {
    name: "Moldova",
    isoCode: "MD",
    currencyCode: "MDL",
    currencyName: "Moldovan Leu",
    phoneCode: "+373",
    flag: "🇲🇩",
  },
  {
    name: "Monaco",
    isoCode: "MC",
    currencyCode: "EUR",
    currencyName: "Euro",
    phoneCode: "+377",
    flag: "🇲🇨",
  },
  {
    name: "Mongolia",
    isoCode: "MN",
    currencyCode: "MNT",
    currencyName: "Tugrik",
    phoneCode: "+976",
    flag: "🇲🇳",
  },
  {
    name: "Montenegro",
    isoCode: "ME",
    currencyCode: "EUR",
    currencyName: "Euro",
    phoneCode: "+382",
    flag: "🇲🇪",
  },
  {
    name: "Montserrat",
    isoCode: "MS",
    currencyCode: "XCD",
    currencyName: "East Caribbean Dollar",
    phoneCode: "+1-664",
    flag: "🇲🇸",
  },
  {
    name: "Morocco",
    isoCode: "MA",
    currencyCode: "MAD",
    currencyName: "Moroccan Dirham",
    phoneCode: "+212",
    flag: "🇲🇦",
  },
  {
    name: "Mozambique",
    isoCode: "MZ",
    currencyCode: "MZN",
    currencyName: "Metical",
    phoneCode: "+258",
    flag: "🇲🇿",
  },
  {
    name: "Myanmar",
    isoCode: "MM",
    currencyCode: "MMK",
    currencyName: "Kyat",
    phoneCode: "+95",
    flag: "🇲🇲",
  },
  {
    name: "Namibia",
    isoCode: "NA",
    currencyCode: "NAD",
    currencyName: "Namibian Dollar",
    phoneCode: "+264",
    flag: "🇳🇦",
  },
  {
    name: "Nauru",
    isoCode: "NR",
    currencyCode: "AUD",
    currencyName: "Australian Dollar",
    phoneCode: "+674",
    flag: "🇳🇷",
  },
  {
    name: "Nepal",
    isoCode: "NP",
    currencyCode: "NPR",
    currencyName: "Nepalese Rupee",
    phoneCode: "+977",
    flag: "🇳🇵",
  },
  {
    name: "Netherlands",
    isoCode: "NL",
    currencyCode: "EUR",
    currencyName: "Euro",
    phoneCode: "+31",
    flag: "🇳🇱",
  },
  {
    name: "New Caledonia",
    isoCode: "NC",
    currencyCode: "XPF",
    currencyName: "CFP Franc",
    phoneCode: "+687",
    flag: "🇳🇨",
  },
  {
    name: "New Zealand",
    isoCode: "NZ",
    currencyCode: "NZD",
    currencyName: "New Zealand Dollar",
    phoneCode: "+64",
    flag: "🇳🇿",
  },
  {
    name: "Nicaragua",
    isoCode: "NI",
    currencyCode: "NIO",
    currencyName: "Córdoba",
    phoneCode: "+505",
    flag: "🇳🇮",
  },
  {
    name: "Niger",
    isoCode: "NE",
    currencyCode: "XOF",
    currencyName: "West African CFA Franc",
    phoneCode: "+227",
    flag: "🇳🇪",
  },
  {
    name: "Nigeria",
    isoCode: "NG",
    currencyCode: "NGN",
    currencyName: "Naira",
    phoneCode: "+234",
    flag: "🇳🇬",
  },
  {
    name: "Niue",
    isoCode: "NU",
    currencyCode: "NZD",
    currencyName: "New Zealand Dollar",
    phoneCode: "+683",
    flag: "🇳🇺",
  },
  {
    name: "Norfolk Island",
    isoCode: "NF",
    currencyCode: "AUD",
    currencyName: "Australian Dollar",
    phoneCode: "+672",
    flag: "🇳🇫",
  },
  {
    name: "North Macedonia",
    isoCode: "MK",
    currencyCode: "MKD",
    currencyName: "Denar",
    phoneCode: "+389",
    flag: "🇲🇰",
  },
  {
    name: "Northern Mariana Islands",
    isoCode: "MP",
    currencyCode: "USD",
    currencyName: "US Dollar",
    phoneCode: "+1-670",
    flag: "🇲🇵",
  },
  {
    name: "Norway",
    isoCode: "NO",
    currencyCode: "NOK",
    currencyName: "Norwegian Krone",
    phoneCode: "+47",
    flag: "🇳🇴",
  },
  {
    name: "Oman",
    isoCode: "OM",
    currencyCode: "OMR",
    currencyName: "Omani Rial",
    phoneCode: "+968",
    flag: "🇴🇲",
  },
  {
    name: "Pakistan",
    isoCode: "PK",
    currencyCode: "PKR",
    currencyName: "Pakistani Rupee",
    phoneCode: "+92",
    flag: "🇵🇰",
  },
  {
    name: "Palau",
    isoCode: "PW",
    currencyCode: "USD",
    currencyName: "US Dollar",
    phoneCode: "+680",
    flag: "🇵🇼",
  },
  {
    name: "Palestine, State of",
    isoCode: "PS",
    currencyCode: "ILS",
    currencyName: "New Shekel",
    phoneCode: "+970",
    flag: "🇵🇸",
  },
  {
    name: "Panama",
    isoCode: "PA",
    currencyCode: "PAB",
    currencyName: "Balboa",
    phoneCode: "+507",
    flag: "🇵🇦",
  },
  {
    name: "Papua New Guinea",
    isoCode: "PG",
    currencyCode: "PGK",
    currencyName: "Kina",
    phoneCode: "+675",
    flag: "🇵🇬",
  },
  {
    name: "Paraguay",
    isoCode: "PY",
    currencyCode: "PYG",
    currencyName: "Guarani",
    phoneCode: "+595",
    flag: "🇵🇾",
  },
  {
    name: "Peru",
    isoCode: "PE",
    currencyCode: "PEN",
    currencyName: "Sol",
    phoneCode: "+51",
    flag: "🇵🇪",
  },
  {
    name: "Philippines",
    isoCode: "PH",
    currencyCode: "PHP",
    currencyName: "Philippine Peso",
    phoneCode: "+63",
    flag: "🇵🇭",
  },
  {
    name: "Pitcairn",
    isoCode: "PN",
    currencyCode: "NZD",
    currencyName: "New Zealand Dollar",
    phoneCode: "+64",
    flag: "🇵🇳",
  },
  {
    name: "Poland",
    isoCode: "PL",
    currencyCode: "PLN",
    currencyName: "Zloty",
    phoneCode: "+48",
    flag: "🇵🇱",
  },
  {
    name: "Portugal",
    isoCode: "PT",
    currencyCode: "EUR",
    currencyName: "Euro",
    phoneCode: "+351",
    flag: "🇵🇹",
  },
  {
    name: "Puerto Rico",
    isoCode: "PR",
    currencyCode: "USD",
    currencyName: "US Dollar",
    phoneCode: "+1-787",
    flag: "🇵🇷",
  },
  {
    name: "Qatar",
    isoCode: "QA",
    currencyCode: "QAR",
    currencyName: "Qatari Rial",
    phoneCode: "+974",
    flag: "🇶🇦",
  },
  {
    name: "Réunion",
    isoCode: "RE",
    currencyCode: "EUR",
    currencyName: "Euro",
    phoneCode: "+262",
    flag: "🇷🇪",
  },
  {
    name: "Romania",
    isoCode: "RO",
    currencyCode: "RON",
    currencyName: "Romanian Leu",
    phoneCode: "+40",
    flag: "🇷🇴",
  },
  {
    name: "Russian Federation",
    isoCode: "RU",
    currencyCode: "RUB",
    currencyName: "Russian Rubles",
    phoneCode: "+7",
    flag: "🇷🇺",
  },
  {
    name: "Rwanda",
    isoCode: "RW",
    currencyCode: "RWF",
    currencyName: "Rwandan Franc",
    phoneCode: "+250",
    flag: "🇷🇼",
  },
  {
    name: "Saint Barthélemy",
    isoCode: "BL",
    currencyCode: "EUR",
    currencyName: "Euro",
    phoneCode: "+590",
    flag: "🇧🇱",
  },
  {
    name: "Saint Helena, Ascension and Tristan da Cunha",
    isoCode: "SH",
    currencyCode: "SHP",
    currencyName: "Saint Helena Pound",
    phoneCode: "+290",
    flag: "🇸🇭",
  },
  {
    name: "Saint Kitts and Nevis",
    isoCode: "KN",
    currencyCode: "XCD",
    currencyName: "East Caribbean Dollar",
    phoneCode: "+1-869",
    flag: "🇰🇳",
  },
  {
    name: "Saint Lucia",
    isoCode: "LC",
    currencyCode: "XCD",
    currencyName: "East Caribbean Dollar",
    phoneCode: "+1-758",
    flag: "🇱🇨",
  },
  {
    name: "Saint Martin (French part)",
    isoCode: "MF",
    currencyCode: "EUR",
    currencyName: "Euro",
    phoneCode: "+590",
    flag: "🇲🇫",
  },
  {
    name: "Saint Pierre and Miquelon",
    isoCode: "PM",
    currencyCode: "EUR",
    currencyName: "Euro",
    phoneCode: "+508",
    flag: "🇵🇲",
  },
  {
    name: "Saint Vincent and the Grenadines",
    isoCode: "VC",
    currencyCode: "XCD",
    currencyName: "East Caribbean Dollar",
    phoneCode: "+1-784",
    flag: "🇻🇨",
  },
  {
    name: "Samoa",
    isoCode: "WS",
    currencyCode: "WST",
    currencyName: "Tala",
    phoneCode: "+685",
    flag: "🇼🇸",
  },
  {
    name: "San Marino",
    isoCode: "SM",
    currencyCode: "EUR",
    currencyName: "Euro",
    phoneCode: "+378",
    flag: "🇸🇲",
  },
  {
    name: "Sao Tome and Principe",
    isoCode: "ST",
    currencyCode: "STN",
    currencyName: "Dobra",
    phoneCode: "+239",
    flag: "🇸🇹",
  },
  {
    name: "Saudi Arabia",
    isoCode: "SA",
    currencyCode: "SAR",
    currencyName: "Saudi Riyal",
    phoneCode: "+966",
    flag: "🇸🇦",
  },
  {
    name: "Senegal",
    isoCode: "SN",
    currencyCode: "XOF",
    currencyName: "West African CFA Franc",
    phoneCode: "+221",
    flag: "🇸🇳",
  },
  {
    name: "Serbia",
    isoCode: "RS",
    currencyCode: "RSD",
    currencyName: "Serbian Dinar",
    phoneCode: "+381",
    flag: "🇷🇸",
  },
  {
    name: "Seychelles",
    isoCode: "SC",
    currencyCode: "SCR",
    currencyName: "Seychellois Rupee",
    phoneCode: "+248",
    flag: "🇸🇨",
  },
  {
    name: "Sierra Leone",
    isoCode: "SL",
    currencyCode: "SLE",
    currencyName: "Leone",
    phoneCode: "+232",
    flag: "🇸🇱",
  },
  {
    name: "Singapore",
    isoCode: "SG",
    currencyCode: "SGD",
    currencyName: "Singapore Dollar",
    phoneCode: "+65",
    flag: "🇸🇬",
  },
  {
    name: "Sint Maarten (Dutch part)",
    isoCode: "SX",
    currencyCode: "ANG",
    currencyName: "Netherlands Antillean Guilder",
    phoneCode: "+1-721",
    flag: "🇸🇽",
  },
  {
    name: "Slovakia",
    isoCode: "SK",
    currencyCode: "EUR",
    currencyName: "Euro",
    phoneCode: "+421",
    flag: "🇸🇰",
  },
  {
    name: "Slovenia",
    isoCode: "SI",
    currencyCode: "EUR",
    currencyName: "Euro",
    phoneCode: "+386",
    flag: "🇸🇮",
  },
  {
    name: "Solomon Islands",
    isoCode: "SB",
    currencyCode: "SBD",
    currencyName: "Solomon Islands Dollar",
    phoneCode: "+677",
    flag: "🇸🇧",
  },
  {
    name: "Somalia",
    isoCode: "SO",
    currencyCode: "SOS",
    currencyName: "Somali Shilling",
    phoneCode: "+252",
    flag: "🇸🇴",
  },
  {
    name: "South Africa",
    isoCode: "ZA",
    currencyCode: "ZAR",
    currencyName: "Rand",
    phoneCode: "+27",
    flag: "🇿🇦",
  },
  {
    name: "South Georgia and the South Sandwich Islands",
    isoCode: "GS",
    currencyCode: "GBP",
    currencyName: "Pound Sterling",
    phoneCode: "+500",
    flag: "🇬🇸",
  },
  {
    name: "South Sudan",
    isoCode: "SS",
    currencyCode: "SSP",
    currencyName: "South Sudanese Pound",
    phoneCode: "+211",
    flag: "🇸🇸",
  },
  {
    name: "Spain",
    isoCode: "ES",
    currencyCode: "EUR",
    currencyName: "Euro",
    phoneCode: "+34",
    flag: "🇪🇸",
  },
  {
    name: "Sri Lanka",
    isoCode: "LK",
    currencyCode: "LKR",
    currencyName: "Sri Lankan Rupee",
    phoneCode: "+94",
    flag: "🇱🇰",
  },
  {
    name: "Sudan",
    isoCode: "SD",
    currencyCode: "SDG",
    currencyName: "Sudanese Pound",
    phoneCode: "+249",
    flag: "🇸🇩",
  },
  {
    name: "Suriname",
    isoCode: "SR",
    currencyCode: "SRD",
    currencyName: "Surinamese Dollar",
    phoneCode: "+597",
    flag: "🇸🇷",
  },
  {
    name: "Svalbard and Jan Mayen",
    isoCode: "SJ",
    currencyCode: "NOK",
    currencyName: "Norwegian Krone",
    phoneCode: "+47",
    flag: "🇸🇯",
  },
  {
    name: "Sweden",
    isoCode: "SE",
    currencyCode: "SEK",
    currencyName: "Swedish Krona",
    phoneCode: "+46",
    flag: "🇸🇪",
  },
  {
    name: "Switzerland",
    isoCode: "CH",
    currencyCode: "CHF",
    currencyName: "Swiss Franc",
    phoneCode: "+41",
    flag: "🇨🇭",
  },
  {
    name: "Syrian Arab Republic",
    isoCode: "SY",
    currencyCode: "SYP",
    currencyName: "Syrian Pound",
    phoneCode: "+963",
    flag: "🇸🇾",
  },
  {
    name: "Taiwan",
    isoCode: "TW",
    currencyCode: "TWD",
    currencyName: "New Taiwan Dollar",
    phoneCode: "+886",
    flag: "🇹🇼",
  },
  {
    name: "Tajikistan",
    isoCode: "TJ",
    currencyCode: "TJS",
    currencyName: "Somoni",
    phoneCode: "+992",
    flag: "🇹🇯",
  },
  {
    name: "Tanzania",
    isoCode: "TZ",
    currencyCode: "TZS",
    currencyName: "Tanzanian Shilling",
    phoneCode: "+255",
    flag: "🇹🇿",
  },
  {
    name: "Thailand",
    isoCode: "TH",
    currencyCode: "THB",
    currencyName: "Baht",
    phoneCode: "+66",
    flag: "🇹🇭",
  },
  {
    name: "Timor-Leste",
    isoCode: "TL",
    currencyCode: "USD",
    currencyName: "US Dollar",
    phoneCode: "+670",
    flag: "🇹🇱",
  },
  {
    name: "Togo",
    isoCode: "TG",
    currencyCode: "XOF",
    currencyName: "West African CFA Franc",
    phoneCode: "+228",
    flag: "🇹🇬",
  },
  {
    name: "Tokelau",
    isoCode: "TK",
    currencyCode: "NZD",
    currencyName: "New Zealand Dollar",
    phoneCode: "+690",
    flag: "🇹🇰",
  },
  {
    name: "Tonga",
    isoCode: "TO",
    currencyCode: "TOP",
    currencyName: "Pa’anga",
    phoneCode: "+676",
    flag: "🇹🇴",
  },
  {
    name: "Trinidad and Tobago",
    isoCode: "TT",
    currencyCode: "TTD",
    currencyName: "Trinidad and Tobago Dollar",
    phoneCode: "+1-868",
    flag: "🇹🇹",
  },
  {
    name: "Tunisia",
    isoCode: "TN",
    currencyCode: "TND",
    currencyName: "Tunisian Dinar",
    phoneCode: "+216",
    flag: "🇹🇳",
  },
  {
    name: "Türkiye",
    isoCode: "TR",
    currencyCode: "TRY",
    currencyName: "Turkish Lira",
    phoneCode: "+90",
    flag: "🇹🇷",
  },
  {
    name: "Turkmenistan",
    isoCode: "TM",
    currencyCode: "TMT",
    currencyName: "Manat",
    phoneCode: "+993",
    flag: "🇹🇲",
  },
  {
    name: "Turks and Caicos Islands",
    isoCode: "TC",
    currencyCode: "USD",
    currencyName: "US Dollar",
    phoneCode: "+1-649",
    flag: "🇹🇨",
  },
  {
    name: "Tuvalu",
    isoCode: "TV",
    currencyCode: "AUD",
    currencyName: "Australian Dollar",
    phoneCode: "+688",
    flag: "🇹🇻",
  },
  {
    name: "Uganda",
    isoCode: "UG",
    currencyCode: "UGX",
    currencyName: "Ugandan Shilling",
    phoneCode: "+256",
    flag: "🇺🇬",
  },
  {
    name: "Ukraine",
    isoCode: "UA",
    currencyCode: "UAH",
    currencyName: "Hryvnia",
    phoneCode: "+380",
    flag: "🇺🇦",
  },
  {
    name: "United Arab Emirates",
    isoCode: "AE",
    currencyCode: "AED",
    currencyName: "UAE Dirham",
    phoneCode: "+971",
    flag: "🇦🇪",
  },
  {
    name: "United Kingdom",
    isoCode: "GB",
    currencyCode: "GBP",
    currencyName: "Pound Sterling",
    phoneCode: "+44",
    flag: "🇬🇧",
  },
  {
    name: "United States",
    isoCode: "US",
    currencyCode: "USD",
    currencyName: "US Dollar",
    phoneCode: "+1",
    flag: "🇺🇸",
  },
  {
    name: "United States Minor Outlying Islands",
    isoCode: "UM",
    currencyCode: "USD",
    currencyName: "US Dollar",
    phoneCode: "+1",
    flag: "🇺🇲",
  },
  {
    name: "Uruguay",
    isoCode: "UY",
    currencyCode: "UYU",
    currencyName: "Uruguayan Peso",
    phoneCode: "+598",
    flag: "🇺🇾",
  },
  {
    name: "Uzbekistan",
    isoCode: "UZ",
    currencyCode: "UZS",
    currencyName: "Uzbekistani Som",
    phoneCode: "+998",
    flag: "🇺🇿",
  },
  {
    name: "Vanuatu",
    isoCode: "VU",
    currencyCode: "VUV",
    currencyName: "Vatu",
    phoneCode: "+678",
    flag: "🇻🇺",
  },
  {
    name: "Venezuela",
    isoCode: "VE",
    currencyCode: "VES",
    currencyName: "Bolívar",
    phoneCode: "+58",
    flag: "🇻🇪",
  },
  {
    name: "Viet Nam",
    isoCode: "VN",
    currencyCode: "VND",
    currencyName: "Dong",
    phoneCode: "+84",
    flag: "🇻🇳",
  },
  {
    name: "Virgin Islands (British)",
    isoCode: "VG",
    currencyCode: "USD",
    currencyName: "US Dollar",
    phoneCode: "+1-284",
    flag: "🇻🇬",
  },
  {
    name: "Virgin Islands (U.S.)",
    isoCode: "VI",
    currencyCode: "USD",
    currencyName: "US Dollar",
    phoneCode: "+1-340",
    flag: "🇻🇮",
  },
  {
    name: "Wallis and Futuna",
    isoCode: "WF",
    currencyCode: "XPF",
    currencyName: "CFP Franc",
    phoneCode: "+681",
    flag: "🇼🇫",
  },
  {
    name: "Western Sahara",
    isoCode: "EH",
    currencyCode: "MAD",
    currencyName: "Moroccan Dirham",
    phoneCode: "+212",
    flag: "🇪🇭",
  },
  {
    name: "Yemen",
    isoCode: "YE",
    currencyCode: "YER",
    currencyName: "Yemeni Rial",
    phoneCode: "+967",
    flag: "🇾🇪",
  },
  {
    name: "Zambia",
    isoCode: "ZM",
    currencyCode: "ZMW",
    currencyName: "Kwacha",
    phoneCode: "+260",
    flag: "🇿🇲",
  },
  {
    name: "Zimbabwe",
    isoCode: "ZW",
    currencyCode: "ZWL",
    currencyName: "Zimbabwe Dollar",
    phoneCode: "+263",
    flag: "🇿🇼",
  },
];

export { countries };    export type { Country };

